### ISSUE TITLE
Select set_size

### ISSUE THREAD

**Issue by arneg** [DeutscheSoft/toolkit#10]
The Select widgets sets its width property to the maximum width of any child entry. This requires calculating their outer_width and forces a relayout.

**Comment by boomshop** [comment]
This can be disabled by setting auto_size = false which means that the button element is auto-sized depending on its content or style. Probably setting it to false as default?

**Comment by arneg** [comment]
Do you think its possible to get this autosizing for free by changing the DOM? Why do we not use `<input type=select>` ?

**Comment by boomshop** [comment]
That might work for this particular widget. There are plans to build subclasses with enhanced features from it like d'n'd sortable lists, additional widgets inside each option like delete buttons and the like.
