### ISSUE TITLE
Fader-related stuff

### ISSUE THREAD

**Issue by boomshop** [DeutscheSoft/toolkit#111]
* fader doesn't get a class when dragged, only the handle
* fader doesn't fire any drag-related events when dragged, only useraction
* we probably should have ValueFader (with label and value)

**Comment by arneg** [comment]
First one is a bug, will fix. Second I cannot reproduce. I can add a 'startdrag' event handler and it fires.

**Comment by arneg** [comment]
Regarding the last point. You can easily add them as childwidgets/childelements. The only comment I have is that we should avoid inheriting all the options, but apart from that it should be straighforward. I can do that, if you want.
