### ISSUE TITLE
Circular/Knob/DragValue: basis used multiple times

### ISSUE THREAD

**Issue by boomshop** [DeutscheSoft/toolkit#116]
option.basis is used in Circular to define the arc of all elements. It is also used in DragValue to define the amount of pixels one has to drag to get from min to max. This collides in Knob somehow since it inherits Circular and has a DragValue. This wasn't a problem by now since the 270 degrees for Circular do work very well as 270 pixel length to drag between min and max.

This is the reason why one has to explicitly set a basis in ValueButton but not in ValueKnob to make it work OOTB.

Additionally we should add a default of 270 pixels to DragValue.

**Comment by arneg** [comment]
I think the plan for the future is to inherit less options and rely on the child options syntax, for instance "circular.basis" etc. We should do this switch at some point, but it would not be backwards compatible.

**Comment by boomshop** [comment]
However we deal with inheritance of options, using `basis` for different purposes (opening angle and distance for dragvalue) is not cool. The latest commit adds a new option `angle` to circular, replacing the current use of `basis` for the opening angle. I added a note about the changes in the API to CHANGES.
