### ISSUE TITLE
DragValue: awkward behavior

### ISSUE THREAD

**Issue by boomshop** [DeutscheSoft/toolkit#117]
The latest changes to polar setting in DragValue introduce a strange behavior: Dragging along the angle set via options.rotation has a reasonable impact on the value. Changing the angle of dragging results in less impact on the change in value. Expected behavior is that dragging in any angle not covered by options.blind_angle has the same impact on the change in value.

**Comment by arneg** [comment]
Will look at it.

**Comment by arneg** [comment]
Should be fixed.
