### ISSUE TITLE
Chart: if key is set on init, two group elements are created

### ISSUE THREAD

**Issue by boomshop** [DeutscheSoft/toolkit#124]

**Comment by boomshop** [comment]
Research revealed that this is triggered by`base.js line 745 ff.`:
```
add_static_event(widget, "initialized", function() {
    /* we do not want to trash the class cache */
    this[index] = null;
    this.set(show_option, this.options[show_option]);
});
```
If there are more than one `ChildElement`s hooking on the same option for showing/hiding the procedure is (problems in bold font):

- static events for `set_[show_option]` are added for checking/adding/removing the elements
- `initialized` hook is called for first child which nulls `this[index]` and sets the option
- `set_[show_option]` is called for first element
- test if `this[index]` is available -> `null` (as set in `initialized` handler)
- first element is created and added as `this[index]`
- `set_[show_option]` is called for second element
- test if `this[index]` is available -> `undefined`
- second element is created and added as `this[index]`
- `initialized` hook is called for first child **which nulls `this[index]` (this means the element is still existent but not known by `this` anymore)** and sets the option
- `set_[show_option]` is called for first element
- test if `this[index]` is available -> `true` (no action)
- `set_[show_option]` is called for second element
- test if `this[index]` is available -> **`null` (as set in `initialized` handler)**
- second element is created **again** and added as `this[index]`

**So question is:** why is line 746 setting `this[index] = null` explicitly?

**Comment by arneg** [comment]
Do you use the same name for both child widgets? That would not be supported. You need to name them differently. They can still be hidden/shown using the same option, but you need to specify that explicitly using the 'option' entry.

**Comment by boomshop** [comment]
They are named differently but both have `option: "key"`:

```
TK.ChildElement(TK.Chart, "key_background", {
    option: "key",
    display_check: function(v) {
        return !!v;
    },
    [...]
});

TK.ChildElement(TK.Chart, "key", {
    option: "key",
    display_check: function(v) {
        return !!v;
    },
    [...]
});
```

**Comment by arneg** [comment]
Ok, then that is a bug. Will fix it.

**Comment by boomshop** [comment]
Yep, thanks!
