### ISSUE TITLE
Equalizer remove_bands() function won't properly remove all bands from graph

### ISSUE THREAD

**Issue by MrHarmony** [DeutscheSoft/toolkit#129]
I'm new to toolkit, but playing around with the equalizer widget, I found that the remove_bands() function won't properly remove all bands from the graph but stop midway. 

Changing the corresponding for-loops so that they don't count upwards (while the array length decreases at the same time) but downwards did solve the problem (without in depth inspection/testing though):

for (var i = 0; i < this.bands.length; i++) { ... }
->
for (var i = this.bands.length-1; i >= 0 ; i--) { ... }

for-loop was changed in both remove_bands() and remove_band() functions.
Since I'm new to toolkit I'd rather let those more familiar with the code perform in depth tests and the actual changes, but I hope this contributes in improving the code.

As a side note, might be worth checking if any other widgets contain for-loops counting upwards against a decreasing array-length.

**Comment by boomshop** [comment]
Thanks for the report! Would be nice if you could test the while-loop.
