### ISSUE TITLE
Clock _set_labels()

### ISSUE THREAD

**Issue by arneg** [DeutscheSoft/toolkit#13]
_set_labels() triggers two relayouts. Can this be reduced?

**Comment by boomshop** [comment]
Probably. It calculates the width for the center label and sets it via transfrom. After that it gets its height to re-position the upper and lower label. The height could be calculated in the width calculation, too. That might be not exact pixel-wise which could make dynamic clock sizes with defined background images difficult. But form follows function and the difference would only be 1 or 2 pixels max which an experienced designer could work around easily.
