### ISSUE TITLE
Some confuses from show value

### ISSUE THREAD

**Issue by PLPNghi** [DeutscheSoft/toolkit#131]
Hi,

Many thanks for your previous support.

Today, I'm doing show mvrr level meter. I need to change value after interval time, if current value more than previous value , that's okay. But, when the current value less than previous value, the hold button stand 1 place, not change position.
Ex: - the previous value is 70 and the current value is 71 then the hold button will change position => that's okay
- the previous value is -70 and the current value is -71 then the hold button will stand the previous position => that's my issue.

Could you please support me more?

Thanks

**Comment by PLPNghi** [comment]
One more help, I need to show value with interval, use container of TK.Root, how can I change the value of meter with new values, because I'm removing and creating again component

**Comment by boomshop** [comment]
You can control hold LED manually via `top` if it's a level meter showing only one direction (like `basis` == `min`) or `top` and `bottom` for both hold LED if meter has `basis` > `min` and `basis` < `max` (like the tutorials mvrr demo meter). If I get what you're asking for to me it seems you need to implement your logic with timeouts and stuff into your application layer, setting `value`, `top` and/or `bottom` manually.

For your second question see docs for `TK.MeterBase`, you can set `value` and `label` individually. Use `label_format` as the formatting function for the label. Use `peak_label` to define the behavior of the labels value.

**Comment by PLPNghi** [comment]
Many thanks for your quick response!

**Comment by boomshop** [comment]
You're welcome, hope it helps.
