### ISSUE TITLE
Demo theme, how to replicate it?

### ISSUE THREAD

**Issue by lucianoiam** [DeutscheSoft/toolkit#133]
Hi, is there a place to ask questions? sorry for opening an issue.

I am currently working on a mixer interface for https://github.com/Ardour/ardour . I have no clue on how to get my implementation look similar to this demo http://demo.deuso.de/ISE2016/index.html

So far I got some nice looking plain UIs using "2013" and "plain" styles but would really like to reproduce the above demo superb "pro" look. Are there extra available styles I cannot seem to find?

_EDIT: Not using AWML_

Toolkit:

<img width="1494" alt="Screen Shot 2020-07-19 at 12 21 17" src="https://user-images.githubusercontent.com/930494/87872703-4f04bf80-c9bb-11ea-8fbc-e49817d514e0.png">

Ardour prototype:

<img width="1494" alt="Screen Shot 2020-07-19 at 12 20 48" src="https://user-images.githubusercontent.com/930494/87872706-53c97380-c9bb-11ea-9e09-647cde744bc8.png">

**Comment by boomshop** [comment]
The style for that demo was built exclusively for the project and wasn't released under a free license. Just a thought: if you're trying to build a remote interface for Ardour I'd recommend to replicate the Ardour style for a more seamless users experience.
