### ISSUE TITLE
Use "createDocumentFragment" to build DOM structures wherever possible

### ISSUE THREAD

**Issue by boomshop** [DeutscheSoft/toolkit#25]
https://developer.mozilla.org/en-US/docs/Web/API/Document/createDocumentFragment

**Comment by arneg** [comment]
As a general rule, all `initialize()` methods should append the main DOM node last, after having constructed its DOM entirely. In principle it would also be possible to let this happen by the `redraw()` method, which appends `this.element` to `this.options.container`, however this does not currently work everywhere.
