### ISSUE TITLE
new API for outer_height et. al.

### ISSUE THREAD

**Issue by arneg** [DeutscheSoft/toolkit#27]
outer_height and the other similar functions currently exist in two variants. One variant simply calculates the effective dimensions, while the second variants tries to update the style properties in order to set the effective dimensions. Both variants force a relayout, which is not necessary (but can be fixed). Furthermore, the set-variant forces a style recalculation and it would be nice to somehow seperate that step (e.g. by optionally passing the computed style of the element).

**Comment by boomshop** [comment]
The idea is to get rid of them entirely by using more css-generic stuff. But if they're needed somewhere we should consider the mentioned separation.

**Comment by arneg** [comment]
I think we can close this bug for now. As long as we are using this kind of measurement the current API is good enough. In the current state it does not force a relayout (but still a style recalculation) in set mode, which is almost ideal.
