### ISSUE TITLE
Pager DOM does not scale

### ISSUE THREAD

**Issue by arneg** [DeutscheSoft/toolkit#32]
The current pager implementation, which uses one huge div, which is moved scrolled from one page to the other does harm rendering performance severely. Hiding the pages using `visibility:hidden` does not help.

**Comment by arneg** [comment]
Just to make this more explicit. When changing the Pager implementation to switch pages simply by setting `display:block` and hiding all inactive pages using `display:none` increases rendering times in RUI by a factor of 10 globally. This basically fixes rendering performance on small devices.

**Comment by boomshop** [comment]
The concept I have in mind is as follows:

Pager is a container, pages are containers inside page. They are hidden by default, only the active page is visible. They all have position:absolute;top:0;left:0;width:100%;height:100%. If a page is to be shown it is transform:translateX()-translated to a position outside the pager and moved inwards via CSS transition. When transition ends the old page is hidden. This way we have a nice transition effect without the hassle of invisible elements flowing. CPU usage is high only on transition.

**Comment by arneg** [comment]
Yes, that might be a possible compromise. We still might want to disable the transition effect completely on slow devices and use only `display:none`, `display:block` toggle there. The transition itself is not shown on slow devices anyway, it simply takes 10 times as long to switch the pages.

**Comment by boomshop** [comment]
Perhaps a CSS which disables *all* transition effects like the slowly fading buttons and stuff. Time for a new issue .)

**Comment by boomshop** [comment]
* { transition: all 0s !important };

**Comment by arneg** [comment]
When playing with a simpler pager implementation I also realized that having styles inside the css files which are specific to how the widget works is not very useful. For instance, the width/height properties of the container div are somewhat implementation specific. It makes it easier to change the implementation (maybe even at runtime if frame rates get too low) by having all that set from the widget js implementation.

**Comment by arneg** [comment]
What I would propose is this: Implement your improved idea for a sliding pager with better performance _and_ a simple version, which would be implemented as a simple new class `SimplePager` with a compatible API. We can then rename `Pager` to something like `SlidingPager` and have `Pager` point to either of those two depending on device performance.
