### ISSUE TITLE
Equalizer curve does not automatically scale to height

### ISSUE THREAD

**Issue by arneg** [DeutscheSoft/toolkit#51]
Is this even a bug? Whats the expected behavior. To reproduce, make the equalizer size dynamic in the showcase.

**Comment by boomshop** [comment]
Without taking a look into the code it sounds like the resize doesn't update basis in range_y

**Comment by boomshop** [comment]
I added `resize()` to EQ which invalidates bands. This seems to fix part of the problem (not visually). If one resizes the EQ manually (e.g. `eq.element.style.height="500px"; eq.resize()`) EQ's `redraw()` is called twice. The first time `eq.invalid.bands` is true but `eq.range_y.options.basis` is still the old size (300), the second time `invalid.bands` is false but `eq.range_y.options.basis` is correct (500).

**Comment by arneg** [comment]
resize should probably do the measurements correctly. It is called before any of the redraw() functions and therefore the dom is still clean. will test that.

**Comment by arneg** [comment]
Fixed by 96fafdbc4ccfceb95b05b63bfc5ec48a147d909d
