### ISSUE TITLE
Scale: tutorial doesn't resize on window resize

### ISSUE THREAD

**Issue by boomshop** [DeutscheSoft/toolkit#88]

**Comment by arneg** [comment]
The default scale behavior is to _not_ autosize on its own. An independent autosize behavior should probably be added using an option, which defaults to `true`. All widgets which currently set the size of their scales intenally, have to set that option to `false`.

**Comment by boomshop** [comment]
Scale basis depends on its true size now. Parent widgets are still able to override.
