### ISSUE TITLE
Scale: auto_size for standalone version

### ISSUE THREAD

**Issue by boomshop** [DeutscheSoft/toolkit#89]

**Comment by arneg** [comment]
the `auto_size` option currently adjusts width in vertical scales (and height in horizontal ones) to fit the largest label. Is that really useful, should that not be done in the css by whoever does layout/design?

Anyway, we need another option, which does the scale autosizing.

**Comment by boomshop** [comment]
Yes, this option is from ancient times and can be removed.

**Comment by boomshop** [comment]
Removed.
