### ISSUE TITLE
Make sure the universal 'useraction' event is fired

### ISSUE THREAD

**Issue by arneg** [DeutscheSoft/toolkit#91]
This is not always happening

**Comment by arneg** [comment]
The point of this event is that in most cases this is really what we want, instead of binding to the raw DOM events. In addition, unlike the DOM events, binding to useraction also has the right semantics. We can be sure that the corresponding option has actually been set.

**Comment by arneg** [comment]
Just to elaborate on my previous comment:

What I said above about "useraction" being more useful than binding individual DOM events only specifically refers to those cases where DOM events change an option. Example: "click" on a toggle button changes the state, A "click" event on a buttonarray changes the "show" option, etc. However, the disadvantage of using the DOM event directly is that it is not very relyable, because the way we use DOM events might change in the future or we might decide to introduce "inertia" delays which set options only after some timeout. For me, this is a strong reason for having some event (maybe called "useraction") which fires for every option, which was changed by a user interaction. I think it should have one standard API (option name, option value) and work the same in all widgets. For me it is analogous to the "set" event.

**Comment by boomshop** [comment]
Done for all classes as proposed by Arne.
