### ISSUE TITLE
click vs. doubleclick

### ISSUE THREAD

**Issue by arneg** [DeutscheSoft/toolkit#92]
Some widgets bind both 'click' and 'dblclick', which can lead to broken or browser dependent behavior. It should be possible to control these actions using options. Example: Fader

**Comment by arneg** [comment]
An alternative for the Fader might be to bind dblclick only on the handle. This would at least make the behavior deterministic, at the moment the fader value will jump around depending on how the browser/OS decide to implement dblclick detection.

**Comment by arneg** [comment]
Unfortunately, binding dbclick on the handle only does not work as expected. The underlying problem is that the dblclick event fires on an element even if only the second click hit that element. The result is that the first click will move the fader handle to the mouse position and the second click will trigger the dblclick event on the handle, which will reset the fader.

**Comment by boomshop** [comment]
We could add a value "inertia" to range which smooths out all value changes. This could initially be set to a value an average user interaction (normally dragging which is a continuous movement)  isn't delayed noticeably but a double click doesn't jump to the clicked value first.
