### ISSUE TITLE
MeterBase: canvas drawing not accurate in different zoom levels

### ISSUE THREAD

**Issue by boomshop** [DeutscheSoft/toolkit#99]
It becomes clearly visible with the new light themes. Works well with 100% browser zoom but starts generating thin lines in other zoom levels. Seems it's due to rounding errors while calculating the parts to erase from the canvas.

**Comment by boomshop** [comment]
![tutorial_levelmeter_documentation_chromium](https://cloud.githubusercontent.com/assets/12529902/19170737/dfce8296-8c19-11e6-9690-f31a00a4b47b.png)

**Comment by arneg** [comment]
I am unable to reproduce this with the current layout (even when making the background white to make things more visible). Is it possible that this is triggered by the toolkit-over mask zooming and not the canvas?

**Comment by boomshop** [comment]
Nope, if toolkit-over is removed the stripes are still visible. Let's se if it is reproducible with the new theme.

**Comment by boomshop** [comment]
New style is pushed to master and can be tested against LevelMeter now. Change jsdoc/layout.tmpl line 7 `href="toolkit/styles/2013.css"` to `href="toolkit/styles/plain.css"`

**Comment by arneg** [comment]
Ok, it becomes visible with the new style. However, I think this is a browser bug. If I do anything to make the browser do a full redraw, those artifact lines go away. For instance by changing the tab once. Another way to see that this is not a bug in toolkit: Extract the actual image data from that canvas using getImageData on the context. All pixels are white.

**Comment by arneg** [comment]
It also does not happen in firefox.

**Comment by arneg** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=654700
